version: '3.8'

services:
  pg_database:
    container_name: pg_database_container
    image: pg_database_uacar
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5500"
    networks:
      - default
    ports:
      - '5500:5432'
    environment:
      - POSTGRES_PORT=5500
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=111
      - POSTGRES_DB=dev_test
      - POSTGRES_HOST=pg_database_container
    networks:
      - dev

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5700:80"
    depends_on:
      - pg_database
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - dev

  fast_api:
    build: 
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload
    volumes:
      - ./app:/code/app:z
    ports:
      - "5000:5000"
    environment:
      - HOST_SERVER=pg_database_container
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=111
      - POSTGRES_DB=dev_test
      - POSTGRES_PORT=5500
      - ssl_mode=prefer
    depends_on:
      - pg_database
    restart: always
    networks:
      - dev
  
volumes:
  postgres_data:
  pgadmin-data:

networks:
  dev: